import { Router } from 'express';
import { adminRoutes } from '../modules/admin/index.js';
import { authRoutes } from '../modules/auth/index.js';
import { automationRoutes } from '../modules/automation/index.js';
import { billingRoutes } from '../modules/billing/index.js';
import { catalogRoutes } from '../modules/catalog/index.js';
import { communicationRoutes } from '../modules/communications/index.js';
import { companyRoutes, customizationRoutes } from '../modules/companies/index.js';
import { consentRoutes } from '../modules/consent/index.js';
import { conversationRoutes } from '../modules/conversations/index.js';
import { couponRoutes } from '../modules/coupons/index.js';
import { customerRoutes } from '../modules/customers/index.js';
import { dashboardRoutes } from '../modules/dashboard/index.js';
import { deliveryRoutes } from '../modules/delivery/index.js';
import { notificationRoutes } from '../modules/notifications/index.js';
import { orderRoutes } from '../modules/orders/index.js';
import { paymentEventRoutes } from '../modules/payments/index.js';
import { productRoutes } from '../modules/products/index.js';
import { promotionRoutes } from '../modules/promotions/index.js';
import { transactionRoutes } from '../modules/transactions/index.js';
import { userRoutes } from '../modules/users/index.js';
import { whatsappRoutes } from '../modules/whatsapp/index.js';

const router = Router();

router.use('/admin', adminRoutes);
router.use('/auth', authRoutes);
router.use('/automation', automationRoutes);
router.use('/billing', billingRoutes);
router.use('/catalog', catalogRoutes);
router.use('/communications', communicationRoutes);
router.use('/companies', companyRoutes);
router.use('/company/customization', customizationRoutes);
router.use('/consent', consentRoutes);
router.use('/conversations', conversationRoutes);
router.use('/coupons', couponRoutes);
router.use('/customers', customerRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/delivery', deliveryRoutes);
router.use('/notifications', notificationRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentEventRoutes);
router.use('/products', productRoutes);
router.use('/promotions', promotionRoutes);
router.use('/transactions', transactionRoutes);
router.use('/users', userRoutes);
router.use('/whatsapp', whatsappRoutes);

export default router;